version = 1

[[annotations]]
path = "uv.lock"
SPDX-FileCopyrightText = "2026 Peter Bittner <django@bittner.it>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "insta/templates/*.html"
SPDX-FileCopyrightText = "2026 Peter Bittner <django@bittner.it>"
SPDX-License-Identifier = "GPL-3.0-or-later"
